version: "3.9"

services:

  #-------------------------------------#
  # Wireguard : Fast VPN
  #-------------------------------------#
  wireguard:
    image: lscr.io/linuxserver/wireguard:v1.0.20210914-ls116
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID
      - PGID
      - TZ
      - SERVERURL=wireguard.${DOMAINNAME} #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ${PIDRIVE}/config/wireguard:/config
    ports:
      - 51820:51820/udp
    networks:
      - proxy
      - default
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    
networks:
  proxy:
    external: true
    name: proxy