version: "3.4"

services:

  #rclone:
  #  image: rclone/rclone:1.62.2
  #  container_name: rclone
  #  volumes:
  #    - ${PIDRIVE}/config/backup:/config/rclone
  #  user: "${UID}:${GID}"
  #  command: tail -f /dev/null
  #  restart: unless-stopped

  syncthing:
    image: linuxserver/syncthing:1.24.0
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${PIDRIVE}/config/syncthing:/config
      - ${PIDRIVE}/syncthing:/folders
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - proxy
      - default
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.syncthing-backup.loadbalancer.server.port=8384

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    command: filebrowser --disable-preview-resize --disable-type-detection-by-header --disable-thumbnails --disable-exec --cache-dir /var/cache
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${PIDRIVE}/:/srv    
      - ${PIDRIVE}/config/filebrowser/filebrowser.db:/database/filebrowser.db
    tmpfs:
      - /var/cache
    networks:
      - proxy
      - default
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - sablier.enable=true
      - sablier.group=filebrowser

  piwigo:
    image: linuxserver/piwigo:13.8.0
    container_name: piwigo
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${PIDRIVE}/config/piwigo:/config
      - ${PIDRIVE}/piwigo:/gallery
      - ${PIDRIVE}/syncthing:/syncthing
    networks:
      - default
      - proxy
    restart: unless-stopped    
    labels:
      - traefik.enable=true
      - sablier.enable=true
      - sablier.group=piwigo
  
  piwigo-db:
    container_name: piwigo-db
    image: linuxserver/mariadb:10.11.4
    networks:
      - default
    environment:
      - PUID
      - PGID
      - TZ
      - MYSQL_ROOT_PASSWORD=replace
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo
      - MYSQL_PASSWORD=replace
    volumes:
      - ${PIDRIVE}/config/piwigo-db:/config
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: proxy