version: '3.9'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:v0.7.1-omnibus
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda
    volumes:
      - ${PIDRIVE}/config/scrutiny:/opt/scrutiny/config
      - ${PIDRIVE}/scrutiny:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    restart: unless-stopped
    networks:
      - proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.services.monitoring-scrutiny.loadbalancer.server.port=8080

networks:
  proxy:
    external: true
    name: proxy